Data Wrangling, I
Perform the following operations using Python on any open source dataset (e.g., data.csv)
1. Import all the required Python Libraries.
2. Locate an open source data from the web (e.g., https://www.kaggle.com). Provide a clear
description of the data and its source (i.e., URL of the web site).
3. Load the Dataset into pandas dataframe.
4. Data Preprocessing: check for missing values in the data using pandas isnull(), describe()
function to get some initial statistics. Provide variable descriptions. Types of variables etc.
Check the dimensions of the data frame.
5. Data Formatting and Data Normalization: Summarize the types of variables by checking
the data types (i.e., character, numeric, integer, factor, and logical) of the variables in the
data set. If variables are not in the correct data type, apply proper type conversions.
6. Turn categorical variables into quantitative variables in Python.
In addition to the codes and outputs, explain every operation that you do in the above steps and
explain everything that you do to import/read/scrape the data set.

pandas is a fast, powerful, flexible and easy to use open source data analysis and manipulation tool,
built on top of the Python programming language.

Dataframe : Two-dimensional, size-mutable, potentially heterogeneous tabular data.

In [17]:
# 1. Import all the required Python Libraries

import pandas as pd
import numpy as np
import seaborn as sns #not needed here
import matplotlib.pyplot as plt #not needed here

pandas: For loading and manipulating data.

numpy: For numerical operations, need for mathematical calculations, array, matrix calculations, rn we just are talking about dataset 

seaborn and matplotlib.pyplot: For data visualization (optional but useful).

In [19]:
# 2. Locate an Open Source Data from the Web 

import os

# Check if iris.csv exists in the current directory
print("iris.csv found:", os.path.exists("iris.csv"))
print("Current directory:", os.getcwd())


# This dataset contains 150 records of iris flowers, with 5 attributes:

# SepalLengthCm

# SepalWidthCm

# PetalLengthCm

# PetalWidthCm

# Species (categorical label)

# (150,6) 

# Id is first column starting from 1

iris.csv found: True
Current directory: C:\Users\Anuj\Desktop\DSBDAL\DSBDA-Laboratory\Group A\Practical 1

In [21]:
#3. Load the Dataset into Pandas DataFrame

# url = "https://gist.githubusercontent.com/curran/a08a1080b88344b0c8a7/raw/0e7a9b0a5d22642a06d3d5b9bcbad9890c8ee534/iris.csv"
# df = pd.read_csv(url)
df = pd.read_csv("iris.csv")
# read_csv : Read a comma-separated values (csv) file into DataFrame.
#File names should always be in quotes else it will take it as variable

# Show the first few rows (5) of the dataset to confirm successful loading
print(df.head())

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

4. Data Preprocessing
Now, let's perform some basic preprocessing:

Check for Missing Values: Use isnull() to check for missing data.

Describe the Data: The describe() function gives basic statistics about the numerical columns (mean, min, max, standard deviation, etc.).

In [23]:
# Check for missing values in the dataset
missing_values = df.isnull().sum()


# Describe the dataset
dataset_description = df.describe()

# Display missing values and dataset description
print("Missing Values:\n", missing_values)
print("\nNot null values:\n", df.notnull().sum())
print("\nDataset Description:\n", dataset_description)

# Display the shape (dimensions) of the dataset
print("\nDataset Shape:", df.shape)



print("\nData Types of Variables:")
print(df.dtypes)
print(df.info())

Missing Values:
 Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

Not null values:
 Id               150
SepalLengthCm    150
SepalWidthCm     150
PetalLengthCm    150
PetalWidthCm     150
Species          150
dtype: int64

Dataset Description:
                Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

Dataset Shape: (150, 6)

Data Types of Variables:
Id                 int64
SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species           object
dtype: object
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB
None

Standard deviation is a measure of how spread out the values are in the dataset.

A high standard deviation means the data points are spread out over a large range of values, while a low standard deviation means the data points are close to the mean.

The 25%, 50%, and 75% values represent quartiles of the dataset. These quartiles divide the data into four equal parts, and each quartile contains 25% of the data. Here's a breakdown:

1. 25% (1st Quartile or Q1):
This value represents the first quartile. It is the value below which 25% of the data falls.

Itâ€™s the 25th percentile, meaning that 25% of the data points are less than or equal to this value, and 75% are greater than or equal to it.

In your example, the 25% value for the sepal length is 38.25. This means that 25% of the sepal length values are less than or equal to 38.25.

2. 50% (Median or Q2):
This is the second quartile, also known as the median. It is the middle value of the dataset when all the data points are sorted in ascending order.

50% of the data points fall below this value, and 50% fall above it.

In your dataset, the 50% (median) for the sepal length is 75.5, meaning that half of the sepal length values are less than or equal to 75.5, and half are greater than or equal to it.

3. 75% (3rd Quartile or Q3):
This is the third quartile, representing the value below which 75% of the data falls.

Itâ€™s the 75th percentile, meaning that 75% of the data points are less than or equal to this value, and 25% are greater than or equal to it.

In your example, the 75% value for the sepal length is 112.75, meaning that 75% of the sepal length values are less than or equal to 112.75.

Summary:
25%: First quartile (Q1) â€“ The point below which 25% of the data lies.

50%: Median (Q2) â€“ The middle value, where 50% of the data lies below it and 50% lies above.

75%: Third quartile (Q3) â€“ The point below which 75% of the data lies.

Why Are These Important?

Interquartile Range (IQR): The difference between the 3rd quartile (Q3) and the 1st quartile (Q1) is called the interquartile range (IQR). It is a measure of statistical dispersion and gives you the middle 50% of the data. The formula is:
IQR=Q3âˆ’Q1

Identifying Outliers: The IQR is also useful for detecting outliers in a dataset. Any data points outside the range 
[Q1âˆ’1.5Ã—IQR,Q3+1.5Ã—IQR] are typically considered outlier

In [25]:
#5. Data Formatting and Data Normalization

# Check the data types of the columns
data_types = df.dtypes

print("\nData Types Before Conversion:")
print(df.dtypes)

# Convert specific float columns to integers
#first drop nan values before converting data types
df['SepalLengthCm'] = df['SepalLengthCm'].astype(int)
df['SepalWidthCm'] = df['SepalWidthCm'].astype(int)
df['PetalLengthCm'] = df['PetalLengthCm'].astype(int)
df['PetalWidthCm'] = df['PetalWidthCm'].round().astype(int)
# Note that during conversion, any decimal parts are discarded (for example, 5.8 becomes 5). If you need to round the values before converting to integer, you can use .round() before converting to int. 

# Display the updated DataFrame
print("\nDataFrame with Float Columns Converted to Integer:")
print(df.head())

# Check the data types of all columns after conversion
print("\nData Types After Conversion:")
print(df.dtypes)

print(df.info())

Data Types Before Conversion:
Id                 int64
SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species           object
dtype: object

DataFrame with Float Columns Converted to Integer:
   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1              5             3              1             0  Iris-setosa
1   2              4             3              1             0  Iris-setosa
2   3              4             3              1             0  Iris-setosa
3   4              4             3              1             0  Iris-setosa
4   5              5             3              1             0  Iris-setosa

Data Types After Conversion:
Id                int64
SepalLengthCm     int32
SepalWidthCm      int32
PetalLengthCm     int32
PetalWidthCm      int32
Species          object
dtype: object
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    int32
 2   SepalWidthCm   150 non-null    int32
 3   PetalLengthCm  150 non-null    int32
 4   PetalWidthCm   150 non-null    int32
 5   Species        150 non-null    object
dtypes: int32(4), int64(1), object(1)
memory usage: 4.8+ KB
None

#6 Turn categorical variables into quantitative variables in Python.


### Categorical Variables
Categorical variables represent distinct categories or groups that can take a limited number of values, each of which corresponds to a specific category or label. These variables can be divided into two types:

1. **Nominal**: These variables represent categories without any particular order. For example:
   - **Gender** (Male, Female, Non-binary)
   - **Species** (Cat, Dog, Bird)
   - **Color** (Red, Blue, Green)

   There is no inherent order to these categories, and the numbers or labels are used to group similar data points.

2. **Ordinal**: These variables represent categories with a clear, ordered relationship between them. For example:
   - **Education Level** (High School, Bachelorâ€™s, Masterâ€™s, Ph.D.)
   - **Rating** (Poor, Fair, Good, Excellent)
   - **Rank** (1st, 2nd, 3rd)

   Here, the categories have an inherent ranking or order, but the difference between the categories is not necessarily uniform or measurable.

#### Examples of Categorical Variables:
- Gender: Male, Female
- Education: High School, College, Graduate
- Marital Status: Single, Married, Divorced

### Quantitative Variables
Quantitative variables (also called **numerical variables**) represent measurable quantities and can be expressed with numbers. They can be divided into two types:

1. **Discrete**: These variables can only take specific, distinct values and are typically counted. For example:
   - **Number of children in a family**
   - **Number of cars owned**
   - **Number of students in a classroom**

2. **Continuous**: These variables can take any value within a given range and are typically measured. For example:
   - **Height**
   - **Weight**
   - **Temperature**
   - **Time**

Continuous variables can take infinitely many values between any two numbers (e.g., 1.5, 2.5, 3.7, etc.).

#### Examples of Quantitative Variables:
- Height (in cm or inches)
- Age (in years)
- Income (in dollars)
- Weight (in kilograms)

### Key Differences:
1. **Categorical Variables**:
   - **Nature**: Represent categories or labels.
   - **Example**: Gender, Color, Product Type.
   - **Operations**: You can calculate mode (most frequent category) and use them for grouping or comparison but not for mathematical operations.

2. **Quantitative Variables**:
   - **Nature**: Represent numeric values that can be measured or counted.
   - **Example**: Age, Salary, Distance.
   - **Operations**: You can perform mathematical operations like addition, subtraction, multiplication, and division.

### Conversion of Categorical to Quantitative:
Categorical variables are often converted into numeric format for machine learning models. For instance, you might convert "Male" and "Female" into `0` and `1` (binary encoding), or use techniques like **one-hot encoding** for variables with more than two categories.

In [112]:
# Display the first few rows of the dataframe
print("Original Data:")
print(df.head())

# Convert the 'Species' column to one-hot encoded columns
df_one_hot = pd.get_dummies(df, columns=['Species'], prefix=['Species'])


# Display the updated dataframe
print("\nData with One-Hot Encoding:")
print(df_one_hot.head())

Original Data:
   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1              5             3              1             0  Iris-setosa
1   2              4             3              1             0  Iris-setosa
2   3              4             3              1             0  Iris-setosa
3   4              4             3              1             0  Iris-setosa
4   5              5             3              1             0  Iris-setosa

Data with One-Hot Encoding:
   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0   1              5             3              1             0
1   2              4             3              1             0
2   3              4             3              1             0
3   4              4             3              1             0
4   5              5             3              1             0

   Species_Iris-setosa  Species_Iris-versicolor  Species_Iris-virginica
0                 True                    False                   False
1                 True                    False                   False
2                 True                    False                   False
3                 True                    False                   False
4                 True                    False                   False

 Using One-Hot Encoding (for variables with more than 2 categories)
One-Hot Encoding creates a new binary column for each category. For example, for a column with three categories, the column will be split into three binary columns, each indicating whether a category is present for each row.

Explanation:
pd.get_dummies(): This function automatically converts a categorical column into multiple binary columns. Each column represents a category, where 1 indicates the presence of that category (True) and 0 indicates its absence (False) - also known as one-hot encoding.

columns=['species']: Tells pandas which column(s) you want to apply one-hot encoding to â€” in this case, the 'species' column.

prefix=['species']: This adds a prefix to the names of the new dummy columns to make them more readable or avoid confusion.

Summary:
Label Encoding: Converts each category into a unique integer.

One-Hot Encoding: Converts each category into a separate binary (0 or 1) column.

Use Label Encoding when the categorical variable has an inherent order or is binary. Use One-Hot Encoding for nominal categories with no inherent order (such as Species in the Iris dataset).

Label encoding needs sklearn library, one-hot encoding requires just pandas.

In [ ]:
# Or can use : 

df["Species"].replace({"Iris-setosa": 0, "Iris-versicolor": 1, "Iris-virginica": 2}, inplace=True)

# .replace(): The replace() method in pandas is used to replace specific values in a DataFrame or Series. Here, it takes a dictionary that defines which values should be replaced by what. The keys in the dictionary are the values that you want to replace, and the corresponding values are the replacements  

# inplace=True: This tells pandas to modify the original DataFrame directly rather than returning a modified copy. If inplace were set to False (or omitted, as False is the default), it would return a new DataFrame with the changes, leaving the original DataFrame unchanged